<?php

use App\Http\Controllers\AllocationController;
use App\Http\Controllers\ActivityLogController;
use App\Http\Controllers\AssetController;
use App\Http\Controllers\AssetValuationController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BucketController;
use App\Http\Controllers\BudgetCategoryController;
use App\Http\Controllers\BudgetRulesController;
use App\Http\Controllers\CashFlowController;
use App\Http\Controllers\CommitmentController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DecisionJournalController;
use App\Http\Controllers\DemoWorkspaceController;
use App\Http\Controllers\ExportContextController;
use App\Http\Controllers\FinancialSettingsController;
use App\Http\Controllers\FxRateController;
use App\Http\Controllers\GoalController;
use App\Http\Controllers\ImportController;
use App\Http\Controllers\LedgerController;
use App\Http\Controllers\LiabilityBalanceHistoryController;
use App\Http\Controllers\LiabilityController;
use App\Http\Controllers\LiabilityPaymentController;
use App\Http\Controllers\MarketRateController;
use App\Http\Controllers\MonthlyPlansController;
use App\Http\Controllers\MonthlyReviewController;
use App\Http\Controllers\OperationsController;
use App\Http\Controllers\PasswordController;
use App\Http\Controllers\ReconciliationController;
use App\Http\Controllers\SnapshotController;
use App\Http\Controllers\TransactionCategoryController;
use App\Services\FinanceService;
use Illuminate\Support\Facades\Route;

Route::middleware('guest')->group(function (): void {
    Route::get('/login', [AuthController::class, 'login'])->name('login');
    Route::post('/login', [AuthController::class, 'authenticate'])->middleware('throttle:login')->name('login.store');
    Route::get('/forgot-password', [AuthController::class, 'forgot'])->name('password.request');
    Route::post('/forgot-password', [AuthController::class, 'sendResetLink'])->middleware('throttle:password-reset')->name('password.email');
    Route::get('/reset-password/{token}', [AuthController::class, 'showResetForm'])->name('password.reset');
    Route::post('/reset-password', [AuthController::class, 'reset'])->middleware('throttle:password-reset')->name('password.update');
});
Route::post('/logout', [AuthController::class, 'logout'])->middleware('auth')->name('logout');
Route::put('/password', [PasswordController::class, 'update'])->middleware(['auth', 'throttle:password-reset'])->name('password.change');

Route::middleware('auth')->group(function (): void {
    Route::get('/', DashboardController::class)->name('dashboard');
    Route::get('/api/market-rates', [MarketRateController::class, 'index'])->name('api.market-rates');
    Route::post('/market-rates/sync', [MarketRateController::class, 'sync'])->name('market-rates.sync');
    Route::post('/demo/reset', [DemoWorkspaceController::class, 'reset'])->name('demo.reset');
    Route::get('/learn', fn () => Inertia\Inertia::render('learn'))->name('learn.index');
    Route::get('/assets', [AssetController::class, 'index'])->name('assets.index');
    Route::post('/assets', [AssetController::class, 'store'])->name('assets.store');
    Route::put('/assets/{asset}', [AssetController::class, 'update'])->name('assets.update');
    Route::delete('/assets/{asset}', [AssetController::class, 'destroy'])->name('assets.destroy');
    Route::post('/assets/{asset}/restore', [AssetController::class, 'restore'])->name('assets.restore');
    Route::put('/assets/{asset}/allocations', [AssetController::class, 'updateAllocations'])->name('assets.allocations.update');
    Route::get('/buckets', [BucketController::class, 'index'])->name('buckets.index');
    Route::post('/buckets', [BucketController::class, 'store'])->name('buckets.store');
    Route::put('/buckets/{bucket}', [BucketController::class, 'update'])->name('buckets.update');
    Route::delete('/buckets/{bucket}', [BucketController::class, 'destroy'])->name('buckets.destroy');
    Route::post('/buckets/{bucket}/restore', [BucketController::class, 'restore'])->name('buckets.restore');
    Route::put('/buckets/{bucket}/allocations', [BucketController::class, 'updateAllocations'])->name('buckets.allocations.update');
    Route::get('/goals', [GoalController::class, 'index'])->name('goals.index');
    Route::post('/goals', [GoalController::class, 'store'])->name('goals.store');
    Route::put('/goals/{goal}', [GoalController::class, 'update'])->name('goals.update');
    Route::delete('/goals/{goal}', [GoalController::class, 'destroy'])->name('goals.destroy');
    Route::post('/goals/{goal}/restore', [GoalController::class, 'restore'])->name('goals.restore');
    Route::get('/monthly-review', [MonthlyReviewController::class, 'index'])->name('monthly-review.index');
    Route::post('/monthly-review', [MonthlyReviewController::class, 'store'])->name('monthly-review.store');
    Route::post('/monthly-review/derive', [MonthlyReviewController::class, 'derive'])->name('monthly-review.derive');
    Route::delete('/monthly-review/{review}', [MonthlyReviewController::class, 'destroy'])->name('monthly-review.destroy');
    Route::post('/monthly-review/{review}/restore', [MonthlyReviewController::class, 'restore'])->name('monthly-review.restore');
    Route::post('/monthly-review/{review}/close', [MonthlyReviewController::class, 'close'])->name('monthly-review.close');
    Route::post('/monthly-review/{review}/prepare-next', [MonthlyReviewController::class, 'prepareNext'])->name('monthly-review.prepare-next');
    Route::post('/monthly-review/{review}/reopen', [MonthlyReviewController::class, 'reopen'])->name('monthly-review.reopen');
    Route::post('/allocations/{allocationPlan}/sync-actuals', [AllocationController::class, 'syncActuals'])->name('allocations.sync-actuals');
    Route::get('/cash-flow', [CashFlowController::class, 'index'])->name('cash-flow.index');
    Route::post('/cash-flow', [CashFlowController::class, 'store'])->name('cash-flow.store');
    Route::put('/cash-flow/{cashFlow}', [CashFlowController::class, 'update'])->name('cash-flow.update');
    Route::delete('/cash-flow/{cashFlow}', [CashFlowController::class, 'destroy'])->name('cash-flow.destroy');
    Route::post('/cash-flow/{cashFlow}/restore', [CashFlowController::class, 'restore'])->name('cash-flow.restore');
    Route::get('/commitments', [CommitmentController::class, 'index'])->name('commitments.index');
    Route::post('/commitments', [CommitmentController::class, 'store'])->name('commitments.store');
    Route::put('/commitments/{commitment}', [CommitmentController::class, 'update'])->name('commitments.update');
    Route::delete('/commitments/{commitment}', [CommitmentController::class, 'destroy'])->name('commitments.destroy');
    Route::post('/commitments/{commitment}/restore', [CommitmentController::class, 'restore'])->name('commitments.restore');
    Route::get('/liabilities', [LiabilityController::class, 'index'])->name('liabilities.index');
    Route::post('/liabilities', [LiabilityController::class, 'store'])->name('liabilities.store');
    Route::put('/liabilities/{liability}', [LiabilityController::class, 'update'])->name('liabilities.update');
    Route::delete('/liabilities/{liability}', [LiabilityController::class, 'destroy'])->name('liabilities.destroy');
    Route::post('/liabilities/{liability}/restore', [LiabilityController::class, 'restore'])->name('liabilities.restore');
    Route::post('/liabilities/{liability}/payments', [LiabilityPaymentController::class, 'store'])->name('liabilities.payments.store');
    Route::delete('/liability-payments/{payment}', [LiabilityPaymentController::class, 'destroy'])->name('liability-payments.destroy');
    Route::get('/liability-history', [LiabilityBalanceHistoryController::class, 'index'])->name('liability-history.index');
    Route::post('/liability-history', [LiabilityBalanceHistoryController::class, 'store'])->name('liability-history.store');
    Route::put('/liability-history/{history}', [LiabilityBalanceHistoryController::class, 'update'])->name('liability-history.update');
    Route::delete('/liability-history/{history}', [LiabilityBalanceHistoryController::class, 'destroy'])->name('liability-history.destroy');
    Route::post('/liability-history/{history}/restore', [LiabilityBalanceHistoryController::class, 'restore'])->name('liability-history.restore');
    Route::get('/allocations', [AllocationController::class, 'index'])->name('allocations.index');
    Route::get('/monthly-plans', [MonthlyPlansController::class, 'index'])->name('monthly-plans.index');
    Route::get('/monthly-rules', [BudgetRulesController::class, 'index'])->name('monthly-rules.index');
    Route::post('/monthly-rules', [BudgetRulesController::class, 'store'])->name('monthly-rules.store');
    Route::post('/monthly-rules/templates', [BudgetRulesController::class, 'storeTemplate'])->name('monthly-rules.templates.store');
    Route::get('/monthly-rules/templates/{template}/edit', [BudgetRulesController::class, 'edit'])->name('monthly-rules.templates.edit');
    Route::post('/monthly-rules/templates/duplicate', [BudgetRulesController::class, 'duplicate'])->name('monthly-rules.templates.duplicate');
    Route::post('/monthly-rules/templates/{template}/default', [BudgetRulesController::class, 'setDefault'])->name('monthly-rules.templates.default');
    Route::put('/monthly-rules/templates/{template}', [BudgetRulesController::class, 'updateTemplate'])->name('monthly-rules.templates.update');
    Route::post('/monthly-rules/from-plan/{allocationPlan}', [BudgetRulesController::class, 'fromPlan'])->name('monthly-rules.from-plan');
    Route::delete('/monthly-rules/templates/{template}', [BudgetRulesController::class, 'destroy'])->name('monthly-rules.templates.destroy');
    Route::post('/monthly-rules/templates/{template}/restore', [BudgetRulesController::class, 'restore'])->name('monthly-rules.templates.restore');
    Route::get('/budget-categories', [BudgetCategoryController::class, 'index'])->name('budget-categories.index');
    Route::post('/budget-categories', [BudgetCategoryController::class, 'store'])->name('budget-categories.store');
    Route::put('/budget-categories/{budgetCategory}', [BudgetCategoryController::class, 'update'])->name('budget-categories.update');
    Route::delete('/budget-categories/{budgetCategory}', [BudgetCategoryController::class, 'destroy'])->name('budget-categories.destroy');
    Route::post('/budget-categories/{budgetCategory}/restore', [BudgetCategoryController::class, 'restore'])->name('budget-categories.restore');
    Route::post('/allocations', [AllocationController::class, 'store'])->name('allocations.store');
    Route::post('/allocations/{allocationPlan}/close', [AllocationController::class, 'close'])->name('allocations.close');
    Route::post('/allocations/{allocationPlan}/save-as-template', [BudgetRulesController::class, 'fromPlan'])->name('allocations.save-as-template');
    Route::delete('/allocations/{allocationPlan}', [AllocationController::class, 'destroy'])->name('allocations.destroy');
    Route::post('/allocations/{allocationPlan}/restore', [AllocationController::class, 'restore'])->name('allocations.restore');
    Route::get('/allocation-reconciliation', [AllocationController::class, 'reconciliation'])->name('allocation-reconciliation.index');
    Route::get('/snapshots', [SnapshotController::class, 'index'])->name('snapshots.index');
    Route::post('/snapshots', [SnapshotController::class, 'store'])->name('snapshots.store');
    Route::post('/snapshots/historical', [SnapshotController::class, 'historical'])->name('snapshots.historical');
    Route::put('/snapshots/{snapshot}', [SnapshotController::class, 'update'])->name('snapshots.update');
    Route::delete('/snapshots/{snapshot}', [SnapshotController::class, 'destroy'])->name('snapshots.destroy');
    Route::post('/snapshots/{snapshot}/restore', [SnapshotController::class, 'restore'])->name('snapshots.restore');
    Route::get('/export/context', ExportContextController::class)->name('export.context');
    Route::get('/scenarios', fn (FinanceService $finance) => Inertia\Inertia::render('scenarios', ['dashboard' => $finance->dashboard()]))->name('scenarios.index');
    Route::get('/settings/financial', [FinancialSettingsController::class, 'index'])->name('financial-settings.index');
    Route::post('/settings/financial', [FinancialSettingsController::class, 'store'])->name('financial-settings.store');
    Route::put('/settings/financial/{financialSetting}', [FinancialSettingsController::class, 'update'])->name('financial-settings.update');
    Route::delete('/settings/financial/{financialSetting}', [FinancialSettingsController::class, 'destroy'])->name('financial-settings.destroy');
    Route::post('/settings/financial/{financialSetting}/restore', [FinancialSettingsController::class, 'restore'])->name('financial-settings.restore');
    Route::get('/decision-journal', [DecisionJournalController::class, 'index'])->name('decision-journal.index');
    Route::post('/decision-journal', [DecisionJournalController::class, 'store'])->name('decision-journal.store');
    Route::put('/decision-journal/{decisionJournalEntry}', [DecisionJournalController::class, 'update'])->name('decision-journal.update');
    Route::delete('/decision-journal/{decisionJournalEntry}', [DecisionJournalController::class, 'destroy'])->name('decision-journal.destroy');
    Route::post('/decision-journal/{decisionJournalEntry}/restore', [DecisionJournalController::class, 'restore'])->name('decision-journal.restore');
    Route::get('/ledger', [LedgerController::class, 'index'])->name('ledger.index');
    Route::get('/transaction-categories', [TransactionCategoryController::class, 'index'])->name('transaction-categories.index');
    Route::post('/transaction-categories', [TransactionCategoryController::class, 'store'])->name('transaction-categories.store');
    Route::put('/transaction-categories/{category}', [TransactionCategoryController::class, 'update'])->name('transaction-categories.update');
    Route::delete('/transaction-categories/{category}', [TransactionCategoryController::class, 'destroy'])->name('transaction-categories.destroy');
    Route::post('/transaction-categories/{category}/restore', [TransactionCategoryController::class, 'restore'])->name('transaction-categories.restore');
    Route::post('/ledger/accounts', [LedgerController::class, 'storeAccount'])->name('ledger.accounts.store');
    Route::put('/ledger/accounts/{account}', [LedgerController::class, 'updateAccount'])->name('ledger.accounts.update');
    Route::delete('/ledger/accounts/{account}', [LedgerController::class, 'destroyAccount'])->name('ledger.accounts.destroy');
    Route::post('/ledger/accounts/{account}/restore', [LedgerController::class, 'restoreAccount'])->name('ledger.accounts.restore');
    Route::post('/ledger/transactions', [LedgerController::class, 'storeTransaction'])->name('ledger.transactions.store');
    Route::put('/ledger/transactions/{transaction}', [LedgerController::class, 'updateTransaction'])->name('ledger.transactions.update');
    Route::delete('/ledger/transactions/{transaction}', [LedgerController::class, 'destroyTransaction'])->name('ledger.transactions.destroy');
    Route::post('/ledger/transactions/{transaction}/restore', [LedgerController::class, 'restoreTransaction'])->name('ledger.transactions.restore');
    Route::post('/ledger/imports', [ImportController::class, 'store'])->name('ledger.imports.store');
    Route::put('/ledger/imports/{batch}', [ImportController::class, 'updateBatch'])->name('ledger.imports.update');
    Route::post('/ledger/import-rows/{row}/accept', [ImportController::class, 'accept'])->name('ledger.import-rows.accept');
    Route::post('/ledger/import-rows/{row}/reject', [ImportController::class, 'reject'])->name('ledger.import-rows.reject');
    Route::put('/ledger/import-rows/{row}', [ImportController::class, 'updateRow'])->name('ledger.import-rows.update');
    Route::post('/ledger/import-rows/{row}/restore', [ImportController::class, 'restoreRow'])->name('ledger.import-rows.restore');
    Route::delete('/ledger/imports/{batch}', [ImportController::class, 'archive'])->name('ledger.imports.archive');
    Route::post('/ledger/imports/{batch}/restore', [ImportController::class, 'restore'])->name('ledger.imports.restore');
    Route::get('/valuations', [AssetValuationController::class, 'index'])->name('valuations.index');
    Route::post('/valuations', [AssetValuationController::class, 'store'])->name('valuations.store');
    Route::put('/valuations/{valuation}', [AssetValuationController::class, 'update'])->name('valuations.update');
    Route::delete('/valuations/{valuation}', [AssetValuationController::class, 'destroy'])->name('valuations.destroy');
    Route::post('/valuations/{valuation}/restore', [AssetValuationController::class, 'restore'])->name('valuations.restore');
    Route::get('/fx-rates', [FxRateController::class, 'index'])->name('fx-rates.index');
    Route::post('/fx-rates', [FxRateController::class, 'store'])->name('fx-rates.store');
    Route::put('/fx-rates/{fxRate}', [FxRateController::class, 'update'])->name('fx-rates.update');
    Route::delete('/fx-rates/{fxRate}', [FxRateController::class, 'destroy'])->name('fx-rates.destroy');
    Route::post('/fx-rates/{fxRate}/restore', [FxRateController::class, 'restore'])->name('fx-rates.restore');
    Route::get('/reconciliation', ReconciliationController::class)->name('reconciliation.index');
    Route::get('/operations', [OperationsController::class, 'index'])->name('operations.index');
    Route::get('/activity-log', [ActivityLogController::class, 'index'])->name('activity-log.index');
    Route::post('/operations/backups', [OperationsController::class, 'createBackup'])->name('operations.backups.create');
    Route::post('/operations/backups/{backup}/verify', [OperationsController::class, 'verify'])->name('operations.backups.verify');
    Route::get('/operations/backups/{backup}/download', [OperationsController::class, 'download'])->name('operations.backups.download');
    Route::delete('/operations/backups/{backup}', [OperationsController::class, 'archive'])->name('operations.backups.archive');
    Route::post('/operations/backups/{backup}/restore', [OperationsController::class, 'restore'])->name('operations.backups.restore');
    Route::post('/operations/integrity', [OperationsController::class, 'integrity'])->name('operations.integrity');
});
